class RegisterRequest {
  String name;
  String hip;
  int noOfDaysPerWeek;
  String woTime;
  String password;
  String email;
  String fitnessGoal;
  String currentBfp;

  List<String> grains;
  List<String> fruits;
  List<String> carbs;
  List<String> vegetables;
  List<String> nuts;
  List<String> proteins;
  List<String> fats;
  List<String> fibers;
  List<String> focusMuscle;
  List<String> woDays;

  List<String> breakfastFoods;
  List<String> lunchFoods;
  List<String> snackFoods;
  List<String> dinnerFoods;
  List<String> supplements;

  String waist;
  String planType;
  String currentBodyShape;
  String heightUnit;
  String desiredBodyShape;
  String woModeSubOption;
  String targetBfp;
  String currentWeightValue;

  String activityLevel;
  String hipUnit;
  String waistUnit;
  String dobAgeMonth;
  String woGoal;
  String deviceId;
  String woMode;

  String skeletalMuscle;
  String subcutaneousFatPercentage;
  String dobAgeYear;
  String heightValue;
  String howFastToReachGoal;
  String visceralFat;
  String waterWeight;
  String currentWeightUnit;
  String lossGainTargetValue;
  String gender;
  String mealTypeSubOption;
  String mealType;

  RegisterRequest({
    required this.name,
    required this.hip,
    required this.noOfDaysPerWeek,
    required this.woTime,
    required this.password,
    required this.email,
    required this.fitnessGoal,
    required this.currentBfp,
    required this.grains,
    required this.fruits,
    required this.carbs,
    required this.vegetables,
    required this.nuts,
    required this.proteins,
    required this.fats,
    required this.fibers,
    required this.focusMuscle,
    required this.woDays,
    required this.waist,
    required this.planType,
    required this.currentBodyShape,
    required this.heightUnit,
    required this.desiredBodyShape,
    required this.woModeSubOption,
    required this.targetBfp,
    required this.currentWeightValue,
    required this.activityLevel,
    required this.hipUnit,
    required this.waistUnit,
    required this.dobAgeMonth,
    required this.woGoal,
    required this.deviceId,
    required this.woMode,
    required this.skeletalMuscle,
    required this.subcutaneousFatPercentage,
    required this.dobAgeYear,
    required this.heightValue,
    required this.howFastToReachGoal,
    required this.visceralFat,
    required this.waterWeight,
    required this.currentWeightUnit,
    required this.lossGainTargetValue,
    required this.gender,
    required this.mealTypeSubOption,
    required this.mealType,

    required this.breakfastFoods,
    required this.lunchFoods,
    required this.snackFoods,
    required this.dinnerFoods,
    required this.supplements,
  });

  Map<String, dynamic> toJson() => {
        "name": name,
        "hip": hip,
        "no_of_days_per_week": noOfDaysPerWeek,
        "wo_time": woTime,
        "password": password,
        "email": email,
        "fitness_goal": fitnessGoal,
        "current_bfp": currentBfp,
        "grains": grains,
        "fruits": fruits,
        "carbs": carbs,
        "vegetables": vegetables,
        "nuts": nuts,
        "proteins": proteins,
        "fats": fats,
        "fibers": fibers,
        "focus_muscle": focusMuscle,
        "wo_days": woDays,
        "waist": waist,
        "plan_type": planType,
        "current_body_shape": currentBodyShape,
        "height_unit": heightUnit,
        "desired_body_shape": desiredBodyShape,
        "wo_mode_sub_option": woModeSubOption,
        "target_bfp": targetBfp,
        "current_weight_value": currentWeightValue,
        "activity_level": activityLevel,
        "hip_unit": hipUnit,
        "waist_unit": waistUnit,
        "dob_age_month": dobAgeMonth,
        "wo_goal": woGoal,
        "device_id": deviceId,
        "wo_mode": woMode,
        "skeletal_muscle": skeletalMuscle,
        "subcutaneous_fat_percentage": subcutaneousFatPercentage,
        "dob_age_year": dobAgeYear,
        "height_value": heightValue,
        "how_fast_to_reach_goal": howFastToReachGoal,
        "visceral_fat": visceralFat,
        "water_weight": waterWeight,
        "current_weight_unit": currentWeightUnit,
        "loss_gain_target_value": lossGainTargetValue,
        "gender": gender,
        "meal_type_sub_option": mealTypeSubOption,
        "meal_type": mealType,
        "breakfast_food_items_past": breakfastFoods,
        "lunch_food_items_past": lunchFoods,
        "snack_food_items_past": snackFoods,
        "dinner_food_items_past": dinnerFoods,
        "supplements": supplements,
      };
}
